name: .NET Core CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Cambia esto a la versión que necesites

    - name: Restore dependencies
      run: dotnet restore Assembly-CSharp/FlappyBird.sln # Cambia a la ruta correcta

    - name: Build
      run: dotnet build Assembly-CSharp/FlappyBird.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test Assembly-CSharp/FlappyBird.sln --no-build --verbosity normal