name: Build Unity Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write
  deployments: write
  releases: write

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneLinux64
          allowDirtyBuild: true

      # Comprimir build
      - name: Zip Build
        run: |
          cd build/StandaloneLinux64
          zip -r ../../GameBuild.zip .
        
      # Create Release
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "GameBuild.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Release automático del build
            Versión: v${{ github.run_number }}
            Commit: ${{ github.sha }}
          
      # Upload build como artifact (para debug)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-Linux
          path: build/StandaloneLinux64